version: 2.1

orbs:
  docker-rpmbuild: aursu/rpmbuild@1.1.0

workflows:
  ssh2build:
    jobs:
      - docker-rpmbuild/build:
          name: centos7ssh2
          build_service: centos7ssh2
          bintray_uploader: centos7bintray
      - docker-rpmbuild/build:
          name: centos8ssh2
          build_service: centos8ssh2
          bintray_uploader: centos8bintray
      - docker-rpmbuild/build:
          name: centos7ssh2php73
          build_file: docker-compose.php73.yml
          build_service: centos7ssh2php73
          bintray_uploader: centos7bintray
      - docker-rpmbuild/build:
          name: centos8ssh2php73
          build_file: docker-compose.php73.yml
          build_service: centos8ssh2php73
          bintray_uploader: centos8bintray
      - docker-rpmbuild/build:
          name: centos7ssh2php74
          build_file: docker-compose.php74.yml
          build_service: centos7ssh2php74
          bintray_uploader: centos7bintray
      - docker-rpmbuild/build:
          name: centos8ssh2php74
          build_file: docker-compose.php74.yml
          build_service: centos8ssh2php74
          bintray_uploader: centos8bintray

